### ISSUE TITLE
Replace ethabi?

### ISSUE THREAD

**Issue by nanexcool** [dapphub/dapptools#107]
seth runs a modified, outdated version of https://github.com/paritytech/ethabi

https://github.com/dapphub/dapptools/blob/master/overlay.nix#L145

We should explore either trying to update to the latest version or use something different, like https://github.com/ethereumjs/ethereumjs-abi

**Comment by nanexcool** [comment]
Could be fixed along with #82 if using `ethers.js`

**Comment by asymmetric** [comment]
Does `ethers.js` have a way to produce bytecode representations of an ABI? Because that's what we use `ethabi` for IIUC (e.g. for calldata).

`ethers.js` gives us the JSON representation, which we can then feed into `ethabi`. If `ethers.js` does both, then yes we could maybe replace `ethabi` with it (after checking its correctness).

[This](https://docs.ethers.io/ethers.js/html/api-advanced.html#prototype) could be what we're looking for in `ethers.js`.
