### ISSUE TITLE
Output compact AST when running dapp build

### ISSUE THREAD

**Issue by montyly** [dapphub/dapptools#168]
Hi,

Would it be possible to switch by default to the compact AST generation when running `dapp build`? It corresponds to add `compact-format` as a parameter of `--combined-json`.

The difference between the legacy and the compact AST are not well documented, but the compact format was introduced in solidity 0.4.12 and facilitates a lot the work of analyzers. Typically [Slither](https://github.com/crytic/slither/) gives better results with this format.

Thanks!

**Comment by livnev** [comment]
@mhhf @MrChico what do you guys think of this, in terms of `klab` processing the AST?

**Comment by MrChico** [comment]
It would need some massaging to make `compact-format` work with the jumpdest extraction. I did some digging into Slither to see whether they are able to extract the pc value of functions, but it doesn't look like it.

**Comment by montyly** [comment]
Hi @MrChico, what do you mean by pc value of functions? Is it the EVM addresses where the functions begin?

What kind of jumpdest extraction are you doing from the AST? If it's a kind of combination from the AST source map and the combined-json `srcmap`, I could create a slither printer for that.

**Comment by MrChico** [comment]
Hey @montyly, by pc value I mean the program counter pointing to the `JUMPDEST` where an internal function begins, essentially the offset of the instructions. The way I've been extracting this offset is 
1. to look for the function definition in the AST
2. The `src` field of the node gives me a `srcmap`
3. Check which instruction corresponds to that particular `srcmap` value.

It is true that the compact-ast format still provides the `src` field, but since the format is a little different I would need to change the way I do 1.

If this could be handled with a slither printer though, that would be amazing! I've been asking the solidity team to provide the `pc` values of internal functions as part of compiler meta-data, but they don't seem to bullish on it.

**Comment by montyly** [comment]
Hi @MrChico, we are going to investigate how to have this feature in Slither: https://github.com/crytic/slither/issues/209

**Comment by montyly** [comment]
Hi, 

By chance is there any update on this? `dapp` is the last platform that I know of that uses the legacy ast, it would definitely help Slither integration if the compact ast was also provided

We added an evm printer to slither (`slither file.sol --print evm`), but we can add a better interface if that would be still useful for K

**Comment by MrChico** [comment]
Hi @montyly , we are currently exploring migrating to the `--standard-json` format in the coming weeks.
Some of the discussions about this have been taking place at https://github.com/ethereum/solidity/issues/10278.
