### ISSUE TITLE
Event tests don't work

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#18]
<a href="https://github.com/ryepdx"><img src="https://avatars2.githubusercontent.com/u/691597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryepdx](https://github.com/ryepdx)**
_Monday Aug 07, 2017 at 16:54 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/45_

----

Purposely writing failing event tests [per the documentation](https://dapp.readthedocs.io/en/latest/unit_testing.html#testing-events) and they're passing.

**Comment by jparklev** [comment]
Ahh i've run into the same, is `expectEventsExact` deprecated @mbrock?

**Comment by rainbreak** [comment]
@jparklev It isn't deprecated, it just went missing in a tooling upgrade and hasn't reappeared.

**Comment by TimDaub** [comment]
I'm looking for `expectEventsExact`. Upon compilation, dapp tells me that it's an undeclared identifier. However, it is nowhere to be found in [ds-test](https://github.com/dapphub/ds-test).

I know this issue is closed, but could it somehow be introduced again?

**Comment by d-xo** [comment]
dapp.readthedocs.io is totally outdated and unmaintained. Please refer to the [dapp readme](https://github.com/dapphub/dapptools/tree/master/src/dapp#readme) for up to date documentaiton.

**Comment by TimDaub** [comment]
> dapp.readthedocs.io is totally outdated and unmaintained. Please refer to the [dapp readme](https://github.com/dapphub/dapptools/tree/master/src/dapp#readme) for up to date documentaiton.

good to know, I wasn't aware of that. In any case, I've manually added the `expectEventsExact` function into ds-test now but it seems that dapp test doesn't care about the function anymore. I created a purposely failing test that continues to pass.

Since `expectEventsExact` has been removed, is there an alternative? I did a string search for "events" in dapp and hevm's readme, but there weren't any mentions.
