### ISSUE TITLE
`solc 0.5.9` breaks sourcemaps (and god knows what else) 

### ISSUE THREAD

**Issue by livnev** [dapphub/dapptools#236]
This issue is not present in `0.5.6`. `0.5.7-8` are annoying to test because of the `CALLVALUE` nonsense.

**Comment by livnev** [comment]
I've tested `0.5.7` and `0.5.8` and they both still work, so `0.5.9` is the first minor version which introduces this bug. [This](https://github.com/livnev/multipleCalls) is the repo I was using to test.

**Comment by livnev** [comment]
What's bizarre is that [the changelog](https://github.com/ethereum/solidity/blob/develop/Changelog.md#059-2019-05-28) for `0.5.9` doesn't seem to mention anything obviously related to this...

**Comment by MrChico** [comment]
This issue is due to the fact that the compiler metadata format was changed with `0.5.9`. Instead of being prefixed by `-- a1 65 "bzzr0" 0x58 0x20`, we now have `-- a2 65 "bzzr0" 0x58 0x20`. See https://solidity.readthedocs.io/en/v0.5.11/metadata.html and [this commit](https://github.com/dapphub/dapptools/commit/df04392a837180fca2ad55d0ea8eda55929cc72e)

**Comment by livnev** [comment]
fixed by #264
