### ISSUE TITLE
The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by lucas-manuel** [dapphub/dapptools#354]
I'm using the following ~/.sethrc file:
```
export ETH_RPC_ACCOUNTS=yes
export ETH_FROM=0x73789e9Cac27d53A1C24afb3B2baC7d642c6cEaf
export ETH_PASSWORD=<password>
export ETH_KEYSTORE=~/<keystore>
export ETH_RPC_URL="https://kovan.infura.io/v3/<API_KEY>"
export BAT=0x9f8cFB61D3B2aF62864408DD703F9C3BEB55dff7
export FAUCET=0x57aAeAE905376a4B1899bA81364b4cE2519CBfB3
export ETH_GAS=2000000
export BAT=0x9f8cFB61D3B2aF62864408DD703F9C3BEB55dff7
export DAI_TOKEN=0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa
export MCD_JOIN_BAT_A=0x2a4C485B1B8dFb46acCfbeCaF75b6188A59dBd0a
export MCD_VAT=0xbA987bDB501d131f766fEe8180Da5d81b34b69d9
export MCD_JOIN_DAI=0x5AA71a3ae1C0bd6ac27A1f28e1415fFFB6F15B8c
export CDP_MANAGER=0x1476483dD8C35F25e568113C5f70249D3976ba21
export MCD_JUG=0xcbB7718c9F39d05aEEDE1c472ca8Bf804b2f1EaD
```

If I try and send funds (following the tutorial) using: 
`seth send --value 1 0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359`

I get this error:

```
seth-rpc: {"id":1,"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0x73789e9Cac27d53A1C24afb3B2baC7d642c6cEaf","gas":"0x1e8480","to":"0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359","value":"0x1"}]}
seth-rpc: error:   code       -32601
seth-rpc: error:   message    The method eth_sendTransaction does not exist/is not available
```

Any ideas why this could be happening?

**Comment by travs** [comment]
Hey @lucas-manuel , the issue here is the `ETH_RPC_ACCOUNTS` flag being set.

Check out [this](https://github.com/dapphub/dapptools/tree/master/src/seth#key-management-and-signing) part of the readme, where it says:
> If you do want to use the RPC node for key management and signing, set the ETH_RPC_ACCOUNTS variable or use the --rpc-accounts flag.

Basically you would only use that flag if the node you're interacting with has your accounts loaded, which is not the case for infura. If you unset `ETH_RPC_ACCOUNTS` the command should work.

The code should have a check that infura is not being used before sending a `eth_sendTransaction` though, because this method isn't available through their API.

**Comment by lucas-manuel** [comment]
Awesome thanks!
