### ISSUE TITLE
HEVM Fails when Interacting with *some* Vyper Contracts

### ISSUE THREAD

**Issue by 0xpenguin** [dapphub/dapptools#513]
## Intro
HEVM fails when interacting with a [vyper contract](0x5f3b5DfEb7B28CDbD7FAba78963EE202a494e2A2),  however, it works when running it through `ganache`.

MVP repository: https://github.com/0xpenguin/hevm-curve-bug

**Comment by xwvvvvwx** [comment]
I'm not sure exactly where it's coming from, but it seems as though there are some checks around the block number in the curve contract. You can see it here in [this asciinema](https://asciinema.org/a/Ib6kSEbSDVPCddjEokMz1L5wc).

The `hevm` test is failing because `hevm` currenlty doesn't set the block number when using `--rpc`, so it's value is `0` in your test. I can get the `hevm` tests to pass by prepending `DAPP_TEST_NUMBER=$(seth block-number)` to the `dapp test` invocation.

This feels like a bug to me, I think I would expect `hevm` to set the relevant blockchain context to the values from the current block when called with `rpc`. 

@MrChico @livnev what do you think?

**Comment by rainbreak** [comment]
Agree, if we're using --rpc then we should set the block number to the latest or whatever is specified. Similarly for any other environmental numbers that we aren't setting, e.g. timestamp.

**Comment by 0xpenguin** [comment]
Retried it, it works when the blocknumber is specified. Feeling real stupid now....

**Comment by rainbreak** [comment]
@0xpenguin no I think it's a reasonable expectation that `--rpc` would respect the block number from the rpc, unless you explicitly override it. This will be the case once #512 is merged.
