### ISSUE TITLE
hevm didn't handle selfdestruct well?

### ISSUE THREAD

**Issue by guanqun** [dapphub/dapptools#668]
In the unit test, I wrote something like this:

```
contract_a = new ContractA();
contract_a.foo();
contract_a.kill();
contract_a.foo();
```
assuming `kill()` implements the `selfdestruct`.

I noticed that the second `foo()` still can be called, and I can verify that the after the selfdestruct, the extcodesize is still not zero. does it mean that hevm doesn't handle the self destruct well?

**Comment by d-xo** [comment]
As discussed in chat, this is a because `selfdestruct` only schedules the contract for removal at the end of the tx. There does not currently exist a method to manually trigger tx finalization from within an hevm test. 

As a workaround you can put the `kill()` inside of the `setUp` and then have the second call to `foo()` inside of the test body.

**Comment by guanqun** [comment]
Thank you @d-xo  for the explanation here and also the workaround. It works!

For the record, if someone hit the same issue, I've a simple repo to demonstrate how it works. https://github.com/guanqun/hevm-selfdestruct-test

Cheers!
