### ISSUE TITLE
Solidity 0.8.4 Custom Error Support

### ISSUE THREAD

**Issue by TransmissionsDev** [dapphub/dapptools#669]
https://blog.soliditylang.org/2021/04/21/custom-errors/

Currently if a solidity file throws a custom error the dapptools trace will just show the abi encoded hash of the error. 

<img width="692" alt="Screen Shot 2021-06-25 at 9 21 08 AM" src="https://user-images.githubusercontent.com/26209401/123455548-ada4c700-d596-11eb-9c88-0b13b04af5b8.png">

**Comment by d-xo** [comment]
This would be great. 

I think we probably need to do the following:

1. extract all error types from the output json
2. try to abi decode the revert message into each one of the error types
3. if decoding succeeds, print the result as the revert message.

**Comment by d-xo** [comment]
We should also pretty print the various `Panic` revert messages added in solc 0.8.0

**Comment by TransmissionsDev** [comment]
would love to help here but i'm a haskell newbie at best. 

anyway for me to help speed this along (gitcoin? 😝)

**Comment by d-xo** [comment]
I don't think we're interested in gitcoin issue bounties. If you're interested in helping to fund long term development of dapptools then definately reach out via dm.

Alternatively if you're interested in learning your way around hevm then this issue is actually a pretty good place to start, and I would be very happy to coach you through it.

As an overview:

A description of the error type format in the json abi description can be found [here](https://docs.soliditylang.org/en/v0.8.6/abi-spec.html#json), we need to teach hevm to parse this. The solc json parser lives in `Solidity.hs` and we would need to add a new `Error` type with fields mirroring those found in the json output, as well as an `_errorMap :: Map W256 Error` to the [`SolcContract`](https://github.com/dapphub/dapptools/blob/master/src/hevm/src/EVM/Solidity.hs#L135) struct. Then we need to modify both [`readCombinedJSON`](https://github.com/dapphub/dapptools/blob/c20ca2d12b8df01a54665ce24a54957c5e94894c/src/hevm/src/EVM/Solidity.hs#L325) and [`readStdJSON`](https://github.com/dapphub/dapptools/blob/c20ca2d12b8df01a54665ce24a54957c5e94894c/src/hevm/src/EVM/Solidity.hs#L354) to parse the error descriptions out of json and into a `SolcContract`.

The next thing we would need to do would be to add a little glue code in `Dapp.hs` to combine the error maps from each individual `SolcContract` into one big whole project error map. We would do this by adding a new `_dappErrorMap :: Map W256 Error` field to the [`DappInfo`](https://github.com/dapphub/dapptools/blob/c20ca2d12b8df01a54665ce24a54957c5e94894c/src/hevm/src/EVM/Solidity.hs#L354)  struct and concatenate all the errorMaps together in the same way we do for the eventMaps in [`dappInfo`](https://github.com/dapphub/dapptools/blob/c20ca2d12b8df01a54665ce24a54957c5e94894c/src/hevm/src/EVM/Dapp.hs#L91).

Once we have this we can format the errors by modifying the [`showError`](https://github.com/dapphub/dapptools/blob/c20ca2d12b8df01a54665ce24a54957c5e94894c/src/hevm/src/EVM/Format.hs#L125) method to lookup the error in the `errorMap` and do some nice pretty printing if it's found.

**Comment by laurenceday** [comment]
Going to look into this as time permits
