### ISSUE TITLE
Checksum address when reading from ETH_FROM

### ISSUE THREAD

**Issue by tarrencev** [dapphub/dapptools#795]
I ran into an hard to debug issue when using an unchecksummed address with ETH_FROM. It seems like it fails the `ethsign` lookup since `ethsign` uses a checksummed address. I provided a solution here: https://github.com/gakonst/dapptools-template/pull/14 but perhaps we should do something lower level?

**Comment by transmissions11** [comment]
I believe the bug was introduced here: https://github.com/dapphub/dapptools/pull/771/files#diff-1b2c7b5815ec4a184adeea1893c0a9c6b132e96f44dd718061e948cd82aa55b7R61

The grep is case insensitive which is why it fails to find anything if the address isn't checksummed. 

Using a case insensitive grep (via the -I flag iirc) should be a robust fix (or we could alternatively checksum the address and use that as the grep search flag)

**Comment by d-xo** [comment]
Fixed in #796
