### ISSUE TITLE
seth won't generate a function signature with `bytes<n>` as an argument

### ISSUE THREAD

**Issue by ezynda3** [dapphub/dapptools#817]
- When running `seth sig "foo(bytes4)"` I get this error `hevm: could not parse abi argument: 0 : bytes4`
- This is the same for any variation of `bytes` e.g. `bytes`, `bytes32`, etc...
- Strangely arrays of `bytes` work just fine e.g. `seth sig "foo(bytes4[])"` returns `0xe44c352f`

**Comment by mds1** [comment]
`seth sig` works by passing zero-valued dummy arguments to `hevm abiencode` to generate the encoded calldata, then only keeping the function signature. It uses `[]` for empty arrays, and `0` for all other values. So the problem is that `seth sig` uses `0` to represent empty `bytes4`, but it should be passing `0x00000000`

`hevm abiencode` requires bytes arguments to be already padded to their full length. So one solution it to special case each `bytes` type within `seth sig` to pass the correctly sized dummy argument. 

A more robust solution is to have `hevm abiencode` automatically pad values of the form `0x*`, that way you can also do things like `seth calldata "foo(bytes4)()" 0x` which currently fails with `hevm: Data.ByteString.index: index too large: 0, length = 0`
