### ISSUE TITLE
feature request: allow distribution outside of nix

### ISSUE THREAD

**Issue by kathodler** [dapphub/dapptools#870]
I love using dapp tools. I think what you have built here is fantastic. 

It would be great if dapp.tools could be installed using another system aside from nix - I believe this is holding back adoption. Nix is hard to configure in multiuser settings for example. 

Example distribution mechanisms might include:

- docker
- apt
- snap
- brew

My preference would be a docker installation as that has the potential to work anywhere.

**Comment by samrose** [comment]
@kathodler did you know it is possible to build container images that you can distribute with nix?

Example https://thewagner.net/blog/2021/02/25/building-container-images-with-nix/

non-nix users could then use these images for example in a dev setup

**Comment by poma** [comment]
There is already a docker image https://github.com/OdysLam/ddapptools

Looks like it's possible to package all the tools without nix: seth and dapp are mostly shell scripts, hevm is available as a binary.

Some useful info on installation https://twitter.com/owpckcr/status/1457892905893326848 https://twitter.com/owpckcr/status/1457911405500268544

**Comment by samrose** [comment]
I just want to chime in that for distributed applications there are many advantages to consolidating development, packaging and distribution on nix, even where the end user is not using nix.

**Comment by poma** [comment]
Can you elaborate on advantages a little bit? Because in my first impression nix was such a poorly designed system that I still avoid installing it on my OS and have to use dapptools through a docker container which is slower and less convenient. A major reason is that for installing a CLI tool (seth) nix requires to install a LaunchDaemon and create a disk partition (WTF?) and a bunch of other global OS changes. It also insists on installing itself to root dir which none of other apps do. Not respecting even basic standards like FHS is a major red flag. I've tried to google it and turned out they don't plan to change it in future because it's hardcoded everywhere.

My second point is that even if nix is objectively better, having a strong opinion that goes against social consensus (more devs prefer brew to nix currently) can severely hurt adoption. Anecdotal example - me, I was avoiding looking into dapptools for a very long time for that reason even though I knew it's a good tool. We should provide multiple options for devs to do what they want.

**Comment by samrose** [comment]
One of the people who created this project made their case for nix at https://medium.com/dapphub/dapp-tools-and-the-nix-package-manager-c4c692c87310

**Comment by leonprou** [comment]
So about the "superiority" of Nix.
`seth` was the only tool that didn't moved well on the Mac transfer I did. I assume it was because of the efficiency and privacy-wise architecture of Nix. Then on my new Mac Nix just refused to work properly... 
Eventually I needed to fetch and install the components one by one.. Now after a few days breaking my head on this it finally works.

And why I did it?
Because I really like `seth` and a lot of our processes are already use `seth`. So please reconsider, using nix is not the way to increase the usage for dapptools.

**Comment by poma** [comment]
Good thing Forge is catching up with features and doesn't have the downsides like nix dependency

**Comment by kathodler** [comment]
My work around I have come up with is to use this `Dockerfile`:

```Dockerfile
FROM nixos/nix:2.3.12

RUN mkdir -p /app
RUN mkdir -p /nix

ARG UID=1000
ARG GID=1000

ENV USER=me
ENV UID=$UID
ENV GID=$GID

RUN addgroup -S -g $GID $USER && adduser -S -u $UID $USER -G $USER
RUN chown -R me:me /app
RUN chown -R me:me /nix

RUN apk add --no-cache curl jq git

USER $USER
WORKDIR /app

RUN echo $(curl -sS https://api.github.com/repos/dapphub/dapptools/releases/latest | jq -r .tarball_url) > version
RUN nix-env -iA dapp -f $(cat version) && \
nix-env -iA seth -f $(cat version) && \
nix-env -iA hevm -f $(cat version) && \
nix-env -iA ethsign -f $(cat version)

RUN nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_6
RUN git config --global user.email ""
RUN git config --global user.name "anon"

ENV LANG=en_GB.UTF-8
ENV PATH=/home/me/.nix-profile/bin:$PATH
```

With this `docker-compose.yml`:

```yaml

services:
  dt:
    build:
      context: .
    volumes:
      - .:/app
    user: me
```

I can then use commands like this to test my contracts:

```
docker-compose run dt dapp test
```

**Comment by kathodler** [comment]
Thanks for the link @samrose will look into it

**Comment by d-xo** [comment]
I think we're not interested in supporting this at the moment. If nix is problematic for you then I would reccomend using foundry.
