### ISSUE TITLE
hevm: pass all General State Tests

### ISSUE THREAD

**Issue by rainbreak** [dapphub/dapptools#92]
Ethereum has a bunch of general client tests at https://github.com/ethereum/tests. Not all of these are relevant for `hevm`, e.g. consensus, rlp, difficulty, blockchain, as `hevm` is purely an EVM runner.

`hevm` is currently passing the VMTests and has some internal code to support this.

> This is specifically not meant to cover transaction, creation or call processing, or management of the state trie. Indeed at least one implementation tests the VM without calling into any Trie code at all.

> A VM test is based around the notion of executing a single piece of code as part of a transaction, described by the exec portion of the test. 

https://ethereum-tests.readthedocs.io/en/latest/test_types/vm_tests.html

`hevm` does not support running the GeneralStateTests, and it is not clear whether it would pass if it did. However, some opcodes only have coverage in the state tests, notably `CALL` and `CREATE`.

> A state test is based around the notion of executing a single transaction, described by the transaction portion of the test.

https://ethereum-tests.readthedocs.io/en/latest/test_types/state_tests.html

The vm tests do have some basic coverage of call / create: 

> Since these tests are meant only as a basic test of VM operation, the CALL and CREATE instructions are not actually executed. To provide the possibility of testing to guarantee they were actually run at all, a separate portion callcreates details each CALL or CREATE operation in the order they would have been executed. Furthermore, gas required is simply that of the VM execution: the gas cost for transaction processing is excluded.

TODO:
- [x] determine which subset of the state tests is relevant or desirable
- [x] add support for running individual state tests
- [ ] ensure passing all the relevant tests

**Comment by rainbreak** [comment]
see also the ongoing manticore compliance with the state tests: https://github.com/trailofbits/manticore/issues/1167

**Comment by livnev** [comment]
See my WIP on the branch `blockchaintests`. I took the approach of parsing and running the `GeneralStateTests` converted into the more general `BlockchainTests` format, i.e. `BlockchainTests/GeneralStateTests/*/*` in the ethereum tests repo. I also chose to filter for the tests with `"network": "ConstantinopleFix", i.e. the hard for that is live at the time of writing (since currently `hevm` does not support choosing a network regime, though this can be added). All of those tests contain a single block with a single transaction, so it was relatively straightforward to more or less convert them into the `VMTest` paradigm. Transaction handling had to be added.

Current performance:
![screenshot306](https://user-images.githubusercontent.com/3964494/53726688-672b7b80-3e66-11e9-83b7-45e07da9f1f0.png)

Many of the failures can be attributed to some known TODOs:

- [ ] add support for creation txs
- [ ] do gas refunds for `SELFDESTRUCT`
- [ ] add support for `CALLCODE`
- [ ] add missing precompiles:
- - [ ] `SHA256` `RIP160`
- - [ ] `ID`
- - [ ] `MODEXP`
- - [ ] `ECADD` `ECMUL` `ECPAIRING`
- [ ] fix some `ECRECOVER` edge cases
- [ ] fix gas forwarding in `DELEGATECALL`
- [ ] fix unknown `hevm` runtime errors (probably in test harness)

Since `*CALL` and `CREATE*` were previously essentially untested, unsurprisingly there are many failures there.

There are 819 unspecified runtime errors encounted by `hevm` during the parsing or execution of these, which are probably low-hanging fruit and more than likely happened in the test parsing/setup phase.

There is one test `createNameRegistratorPerTxs_d0g0v0` which contains multiple txs.

There also 17 timeouts.

**Comment by rainbreak** [comment]
@livnev can you update with the latest progress and future avenues for compliance?

**Comment by livnev** [comment]
@rainbreak sure, and I'll also rename this issue to "make `hevm` pass all GeneralStateTests":

To update from the previous comment:

![55496440-eadbb200-5636-11e9-9117-264eb62b99b1](https://user-images.githubusercontent.com/3964494/55505940-2f257d00-564c-11e9-9b91-6aa746072492.png)

The low hanging fruit (including the completed ones), as I currently see them are:

- [x] add support for creation txs
- [ ] do gas refunds for `SELFDESTRUCT`
- [x] add support for `CALLCODE`
- [ ] add missing precompiles:
- - [ ] `SHA256` `RIP160`
- - [ ] `ID`
- - [ ] `MODEXP`
- - [ ] `ECADD` `ECMUL` `ECPAIRING`
- [x] fix some `ECRECOVER` edge cases
- [x] fix gas forwarding in `DELEGATECALL`
- [x] fix unknown `hevm` runtime errors (probably in test harness)
- [ ] fix subtle gas mistakes related to `*CALL`
- [ ] fix subtle mistakes in nonces

with the vast majority of the failures coming from the precompiles.

**Comment by livnev** [comment]
Status update (after merging precompiles PR):

![screenshot14](https://user-images.githubusercontent.com/3964494/58693024-26bd9a00-8390-11e9-8aaa-4daddc0a487a.png)

some known failures:

- [ ] 33 `MODEXP` tests failing
- - in 8 of these `hevm` runs out of memory and crashes
- [ ] 19 `ECRECOVER` tests failing
- - appears to be about edge case handling
- [ ] 10 `ECPAIRING` tests failing
- - cause is mysterious, will need to investigate the inputs with `sage`

**Comment by rainbreak** [comment]
fixed in #245
